"""Added columns for ns grading

Revision ID: 0bc60e6abb35
Revises: 39f4ff196d20
Create Date: 2020-11-01 18:07:09.280016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bc60e6abb35'
down_revision = '39f4ff196d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('j_ds_recoreds', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('j_mx_records', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('j_ns_records', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('ns_ip_addresses', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('ns_server_ns_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'ns_server_ns_results')
    op.drop_column('site_runs', 'ns_ip_addresses')
    op.drop_column('site_runs', 'j_ns_records')
    op.drop_column('site_runs', 'j_mx_records')
    op.drop_column('site_runs', 'j_ds_recoreds')
    # ### end Alembic commands ###
