"""Add JSON records

Revision ID: 0cd91b7d480c
Revises: 4b657a3465d7
Create Date: 2020-09-16 22:00:48.553088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cd91b7d480c'
down_revision = '4b657a3465d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('j_caa_records', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('j_dmarc_record', sa.JSON(), nullable=True))
    op.add_column('site_runs', sa.Column('j_txt_records', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sites_domain_idx', 'sites', ['domain'], unique=True)
    op.drop_column('site_runs', 'j_txt_records')
    op.drop_column('site_runs', 'j_dmarc_record')
    op.drop_column('site_runs', 'j_caa_records')
    # ### end Alembic commands ###
