"""Remark Upgrades

Revision ID: 39f4ff196d20
Revises: 0cd91b7d480c
Create Date: 2020-10-20 20:58:16.233685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39f4ff196d20'
down_revision = '0cd91b7d480c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('enum_value', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'remarks', ['remark_type_id', 'enum_value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remarks', type_='unique')
    op.drop_column('remarks', 'enum_value')
    # ### end Alembic commands ###
