"""Add Grading

Revision ID: 4b657a3465d7
Revises: 8554d9883fc1
Create Date: 2020-09-15 21:50:53.006280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b657a3465d7'
down_revision = '8554d9883fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remarks',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('remark_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('remark_level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['remark_type_id'], ['remark_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siterun_remarks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_run_id', sa.BigInteger(), nullable=True),
    sa.Column('remark_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ),
    sa.ForeignKeyConstraint(['site_run_id'], ['site_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('site_runs', sa.Column('caa_grade', sa.BigInteger(), nullable=True))
    op.add_column('site_runs', sa.Column('dmarc_grade', sa.BigInteger(), nullable=True))
    op.add_column('site_runs', sa.Column('spf_grade', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'spf_grade')
    op.drop_column('site_runs', 'dmarc_grade')
    op.drop_column('site_runs', 'caa_grade')
    op.drop_table('siterun_remarks')
    op.drop_table('remarks')
    op.drop_table('remark_types')
    # ### end Alembic commands ###
