"""Add start end end times to site run

Revision ID: 5115a600562c
Revises: b0a3da6447a1
Create Date: 2021-03-20 22:55:22.282733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5115a600562c'
down_revision = 'b0a3da6447a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('site_runs', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'start_time')
    op.drop_column('site_runs', 'end_time')
    # ### end Alembic commands ###
