"""Add Security.txt

Revision ID: 74f603bab0db
Revises: d9105948a0f0
Create Date: 2020-06-20 22:00:45.358671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74f603bab0db'
down_revision = 'd9105948a0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('has_dnssec', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'has_dnssec')
    # ### end Alembic commands ###
