"""Add MS DC

Revision ID: 8554d9883fc1
Revises: 74f603bab0db
Create Date: 2020-07-14 18:37:14.415826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8554d9883fc1'
down_revision = '74f603bab0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('has_msdc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sites_domain_idx', 'sites', ['domain'], unique=True)
    # ### end Alembic commands ###
