"""Add NS grade

Revision ID: 993b64f703aa
Revises: 0bc60e6abb35
Create Date: 2020-11-03 20:21:45.846368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '993b64f703aa'
down_revision = '0bc60e6abb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('ns_grade', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'ns_grade')
    # ### end Alembic commands ###
