"""Inital

Revision ID: d4de8f16b4bd
Revises: 
Create Date: 2020-06-01 20:48:58.816604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4de8f16b4bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmarc_policies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('policy_string', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('search_regex', sa.String(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('start_rank', sa.BigInteger(), nullable=False),
    sa.Column('end_rank', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('current_rank', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spf_policies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('run_rank', sa.BigInteger(), nullable=False),
    sa.Column('caa_record', sa.Text(), nullable=True),
    sa.Column('has_caa', sa.Boolean(), nullable=False),
    sa.Column('has_caa_reporting', sa.Boolean(), nullable=False),
    sa.Column('caa_issue_count', sa.BigInteger(), nullable=True),
    sa.Column('caa_wildcard_count', sa.BigInteger(), nullable=True),
    sa.Column('has_dmarc', sa.Boolean(), nullable=False),
    sa.Column('has_dmarc_aggregate_reporting', sa.Boolean(), nullable=False),
    sa.Column('has_dmarc_forensic_reporting', sa.Boolean(), nullable=False),
    sa.Column('dmarc_policy_id', sa.BigInteger(), nullable=True),
    sa.Column('dmarc_sub_policy_id', sa.BigInteger(), nullable=True),
    sa.Column('dmarc_record', sa.Text(), nullable=True),
    sa.Column('has_spf', sa.Boolean(), nullable=False),
    sa.Column('spf_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('txt_records', sa.Text(), nullable=True),
    sa.Column('ds_records', sa.Text(), nullable=True),
    sa.Column('mx_records', sa.Text(), nullable=True),
    sa.Column('ns_records', sa.Text(), nullable=True),
    sa.Column('email_provider_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['dmarc_policy_id'], ['dmarc_policies.id'], ),
    sa.ForeignKeyConstraint(['dmarc_sub_policy_id'], ['dmarc_policies.id'], ),
    sa.ForeignKeyConstraint(['email_provider_id'], ['email_providers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['spf_policy_id'], ['spf_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_runs')
    op.drop_table('spf_policies')
    op.drop_table('sites')
    op.drop_table('runs')
    op.drop_table('email_providers')
    op.drop_table('dmarc_policies')
    # ### end Alembic commands ###
