"""Add DNSSEC

Revision ID: d9105948a0f0
Revises: facb15278cd0
Create Date: 2020-06-16 20:58:38.839853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9105948a0f0'
down_revision = 'facb15278cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('dnssec_digest_type', sa.SmallInteger(), nullable=True))
    op.add_column('site_runs', sa.Column('dnssec_dnskey_algorithm', sa.SmallInteger(), nullable=True))
    op.add_column('site_runs', sa.Column('dnssec_ds_algorithm', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'dnssec_ds_algorithm')
    op.drop_column('site_runs', 'dnssec_dnskey_algorithm')
    op.drop_column('site_runs', 'dnssec_digest_type')
    # ### end Alembic commands ###
