"""Add DNS Providers

Revision ID: facb15278cd0
Revises: d4de8f16b4bd
Create Date: 2020-06-01 20:52:32.841397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facb15278cd0'
down_revision = 'd4de8f16b4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('search_regex', sa.String(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('site_runs', sa.Column('dns_provider_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'site_runs', 'dns_providers', ['dns_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_runs', type_='foreignkey')
    op.drop_column('site_runs', 'dns_provider_id')
    op.drop_table('dns_providers')
    # ### end Alembic commands ###
