"""Add BIMI fields

Revision ID: fbddede6e2c7
Revises: 8acb10c22e25
Create Date: 2021-03-21 21:29:02.429689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbddede6e2c7'
down_revision = '8acb10c22e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_runs', sa.Column('bimi_grade', sa.BigInteger(), nullable=True))
    op.add_column('site_runs', sa.Column('has_bimi', sa.Boolean(), nullable=True))
    op.add_column('site_runs', sa.Column('j_bimi_records', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_runs', 'j_bimi_records')
    op.drop_column('site_runs', 'has_bimi')
    op.drop_column('site_runs', 'bimi_grade')
    # ### end Alembic commands ###
